### ISSUE TITLE
extra space in echo

### ISSUE THREAD

**Issue by vanhalt** [polegone/gonix#16]
Hi there!

It is really necessary the extra space in the [echo](https://github.com/polegone/gonix/blob/master/echo.go#L8)?

```go
fmt.Printf("%s ", os.Args[i])
```

**Comment by polegone** [comment]
I'm not at my computer at the moment, but I recall doing that so there would be a gap between words when you you use echo like this:

    echo word word word

bryfry has rewritten echo, however.

**Comment by vanhalt** [comment]
wonderful. I submitted a pull request with a mini test suite and added that case :)
