### ISSUE TITLE
dirname: crashing when empty quoted string is passed

### ISSUE THREAD

**Issue by vanhalt** [polegone/gonix#22]
Test crashes when running [empty test](https://github.com/polegone/gonix/blob/master/tests/gonix_test.go#L43) and in command line:

```bash

# Gonix
code/github/gonix$ ./build/dirname ""
panic: runtime error: index out of range

goroutine 1 [running]:
main.main
	code/github/gonix/dirname.go:11

# Gnu
code/github/gonix$ dirname ""
. # notice the . (dot)
```

I suspect that error is [here](https://github.com/polegone/gonix/blob/master/dirname.go#L9-L11)

**Comment by polegone** [comment]
I should test the length of dirname first.
I'll fix that.

**Comment by polegone** [comment]
Should work now.
