### ISSUE TITLE
dirname violates posix

### ISSUE THREAD

**Issue by baverman** [polegone/gonix#24]
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/dirname.html

`dirname /a/b/` and `dirname //a//b//` return `/`

**Comment by polegone** [comment]
Fixed it (I didn't understand Go's [:] notation correctly).

Not closing yet because I haven't done anything to deal with double slashes.

**Comment by baverman** [comment]
There is a reference to XBD Pathname in dirname spec:

> Multiple successive <slash> characters are considered to be the same as one <slash>, except for the case of exactly two leading <slash> characters.

Step 6 about case when the whole "remaining string" equals  `//`.

**Comment by polegone** [comment]
So "dirname //a//b/" should return "//a"?
Currently it returns "/a".

**Comment by vanhalt** [comment]
This is what I get:
```bash
$ dirname //a//b/
//a
```

GNU and BSD versions.

**Comment by baverman** [comment]
If you can't read spec carefully you'd better stop to write coreutils alternative.

**Comment by polegone** [comment]
I am starting to doubt if I'll be able to do all this, actually.

**Comment by vanhalt** [comment]
"can't" and "stop" are strong words that don't help.

**Comment by polegone** [comment]
No, it's not his fault for saying anything. I've just been feeling that I've gotten my self in over my head. The programs seemed easy enough to clone at first, but I'm finding out that there a lot of hidden gotchas and magic tricks.

For example, "os" has a removeall function, but that won't work when I want to run rm verbose or interactively, so I'll have to write my own custom removeall that will confirm each deletion and/or print each file it deletes.

In this specific case, regarding dirname, it seems that relying on the built-in function won't give me the correct results every time, and I may have to write a custom dirname function.

So yeah, I'm just going to try to do what I can regarding gonix, but I admit that it's starting to get difficult for me.

**Comment by vanhalt** [comment]
I am learning go, I am having fun and that is all that matters. Of course we are not going to build something serious, but I am sure that all the knowledge that I will learn from this project will help me in the future to build something useful.

Let's carry on until we can't anymore... :smiley: or when we realise that is not fun anymore.

**Comment by polegone** [comment]
Here's my plan:

I've been working on this for a few weeks already, so I'm already starting to lose interest, especially now that I'm getting into the more difficult parts and it's becoming more stress than fun.  

I think we should work on this for a little while longer (like another 4-6 days) and then merge into go-coreutils, as you and the author suggested. I'm not exactly sure how we'll do it, but I think it's the right thing to do.
