### ISSUE TITLE
Makefile doesn't create build directory before starting

### ISSUE THREAD

**Issue by polegone** [polegone/gonix#25]

**Comment by mibk** [comment]
Is this really an issue? I have found that go build creates directories in the path in `-o` flag by itself. Isn't it your case?

**Comment by polegone** [comment]
make output:

    go build  -o build/base64 base64.go
    # command-line-arguments
    cannot create build/base64
    make: *** [build/base64] Error 2

ls output (after running make):

    base64.go    dirname.go  LICENSE.md  nl.go      seq.go      tee.go    xxd.go
    basename.go  echo.go     Makefile    pwd.go     sha1sum.go  tests     yes.go
    cat.go       false.go    md5sum.go   README.md  sleep.go    touch.go
    cp.go        head.go     mkdir.go    rm.go      tail.go     true.go

**Comment by polegone** [comment]
Works fine now.
