### ISSUE TITLE
Write a Makefile

### ISSUE THREAD

**Issue by iankronquist** [polegone/gonix#3]
You mentioned you wanted one in the README.
I'm going to give this a shot.

**Comment by polegone** [comment]
The makefile doesn't seem to work, but it's a start of something. I'm reverting back to the old README for now.

**Comment by iankronquist** [comment]
hmm It worked for me, but I changed to go compiler to normal go build as opposed to GCC go because I don't have GCC go. What's your issue?

**Comment by polegone** [comment]
It creates an empty directory named "build" and stops.

**Comment by iankronquist** [comment]
Ah, yes. I'll fix that. For now, pass the `-B` flag which forces a build.

**Comment by polegone** [comment]
Okay, it works now, it even used gccgo.

I'll go update the readme.
