### ISSUE TITLE
Mergin with go-coreutils

### ISSUE THREAD

**Issue by vanhalt** [polegone/gonix#36]
@EricLagerg @polegone  Why don't we merge both projects? :smile:

**Comment by EricLagerg** [comment]
I suggested this [on HN](https://news.ycombinator.com/item?id=9516035), and am willing to merge in the projects.

We'd have to discuss some of the minor details, but I'm game.

**Comment by polegone** [comment]
Here's my plan:

I've been working on this for a few weeks already, so I'm already starting to lose interest, especially now that I'm getting into the more difficult parts and it's becoming more stress than fun.

I think we should work on this for a little while longer (like another 4-6 days) and then merge into go-coreutils, as you both suggested. I'm not exactly sure how we'll do it, but I think it's the right thing to do.

**Comment by vanhalt** [comment]
I would say that @EricLagerg can tell us what he would take from this project and we plan based on his comments. Checking his code noticed that there are some commands tested and its dependencies are really well established. What I don't see is a Makefile... but I'm not sure if is because is not needed, I don't know how to build that project... yet.

With that said, seems fun. I'm in.

2 cents

**Comment by EricLagerg** [comment]
@polegone do whatever you feel comfortable doing.
 
I was thinking of something along the lines of...

If/when you decide to merge it, I'll go through and see which utilities I think should be merged over, and you can do the same. Then, you can submit a PR with the specific utilities we agree on.

It'll also be good for me to go through your code, and see how you did things and to see if and where I can improve.

**Comment by EricLagerg** [comment]
@vanhalt You build with `go build ./...` from the root of the repository.

I don't have a Makefile yet, but I've been debating the idea of having one simply because there are some odds and ends (e.g., specific `#defines` on one platform but not another) that need to be tied up.

You're also free to submit code at any time. Right now things tend to break from day-to-day, so I'm not picky. It's a work in progress. I need to write more tests, but I'm trying to figure out how to leverage GNU's testing library. Believe it or not, GNU's coreutils test library has more or nearly the same amount of SLOC than the actual coreutils do.

**Comment by polegone** [comment]
That sounds great to me.

We here will work on our project for a few more days, possibly adding a few more tools, then when I'm ready I'll open an issue on yours and we can start going deciding what to merge.

**Comment by vanhalt** [comment]
Yeah... also it worth to notice that @EricLagerg code seems an exact port from C code. I mean, it is not novice code...

**Comment by EricLagerg** [comment]
@polegone Sounds good!

@vanhalt Yes. Initially it wasn't a transliteration, but as time went on I liked the idea of an easily-manageable, cross-platform version of GNU's version of coreutils.

Transliterating it also has the added benefit of getting to use all of the GNU contributors' genius, while being able to remove some of the legacy code that hinders their utilities.

I've even gone so far as to make sure the output is the same, because (for whatever stupid reason) some programs parse the output of coreutils in order to function correctly. The goal is a cross-platform, drop-in replacement.

**Comment by EricLagerg** [comment]
I also have the `go-gnulib` repository, which I've been using as a library for `go-coreutils` if you're interested ;)

**Comment by polegone** [comment]
I noticed that you used your name in the copyright notice of each program.
I do not want to use my name, and some programs were partly or fully written by other contributers.

How should we deal with this later on when we merge?

**Comment by EricLagerg** [comment]
That is completely up to you. Which license would like to use? My entire go-coreutils is GPLv3, sans for `xxd` because it originally didn't have a license.

**Comment by polegone** [comment]
I also used GPLv3, which suggests a copyright notice.

How does the example I gave above sound?

**Comment by EricLagerg** [comment]
I'm fine with that. Would that just be fore all the new files?

**Comment by polegone** [comment]
Yes, you can keep your files as they are, and right before I merge I'll put that copyright notice on ours.

**Comment by EricLagerg** [comment]
Sounds good to me!

**Comment by polegone** [comment]
I'm finally tired of working on gonix (and I think the others are starting to lose interest too), so I'm going to do some minor touches today and we'll start the process some time tomorrow.

Things I need to do:
* Transition flag to pflag in all the tools
* Add copyright notices
* Make a little file called gonix-contributors.txt and list everyone who has submitted code in there.

Tomorrow, when I'm ready, I'll open an issue on your repository, and then you'll go through my code and pick which apps you want to merge + gonix-contributors.txt

**Comment by vanhalt** [comment]
Honestly I have not lost interest, but I have to admit that to start coding in go-coreutils will take me some time because code right now is really difficult for me. For example I need to learn how to work with Pipes in Go in order to migrate some of the test that we currently have right here... just to mention something =P 

But it sounds like a good plan to be honest and maybe after the merge when you realised that awesome stuff are working you will win interest, again ;)

**Comment by polegone** [comment]
If you'd like to keep working on gonix independently of go-coreutils, then you can fork it (or sync if you've already forked) and continue to work on it; but I truly feel done with it.

**Comment by EricLagerg** [comment]
I'll always take PRs for go-coreutils, and I start getting any regular contributors I'll create issues with varying degrees of difficulty do everybody can help

**Comment by polegone** [comment]
By the way, is it okay that my programs are GPLv3 and yours are GPLv3 *or later*?
I can't really change it now that I've already had other people work on the code.

**Comment by vanhalt** [comment]
I have my fork, where I submit PRs from.

@EricLagerg I will like that, having issues with several degrees to know where would be the best place for me to start, I would really appreciate it.

**Comment by polegone** [comment]
I merged some tools, and am transferring the repo to @EricLagerg 

I guess that's it. I had some fun working on it for a few weeks (and for a little while here), but I'm leaving now.

**Comment by vanhalt** [comment]
All right mate. Thanks to you!

This is all :+1:

**Comment by polegone** [comment]
:+1:
